name: flutter_pos
description: "POS Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.0
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.11
  firebase_core: ^2.24.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/illustration/
    - assets/images/
    - assets/lottie/